#%RAML 0.8

title: RESTopoly jail API
baseUri: http://localhost:8080/
version: 0.1
/jail:
  post:
    description: Imprisiones the given player.
    body:
      application/x-www-form-urlencoded:
        formParameters:
          player:
            description: Name of the player to imprision.
            type: string
    responses:
      200:
  get:
    description: Gives a list with all inmates.
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {"type": "string"},
                    "required": ["name"]
                  }
                }
              }
            example: '[{"name": "Patrick"}, {"name": "Kossakowski"}]'
/jail/{playerId}/dice/{rollN1}/{rollN2}:
  delete:
    description: Removes the given player from jail if he rolled a doublet.
    responses:
      200:
        description: The player was successfully removed from jail.
      409:
        description: The roll was not a doublet. The player remains in jail.
/jail/{playerId}/card:
  delete:
    description: Removes the given player from jail if he uses his "Free of jail" card.
    responses:
      200:
        description: The player was successfully removed from jail.
      409:
        description: The card is not owned by the player. The player remains in jail.
